services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: passlocal1234
      POSTGRES_DB: reservations
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./db:/data/postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user"]
        interval: 10s
        timeout: 5s
        retries: 5