spring:
  application:
    name: reservations
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reservations}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create
